[workspace]
resolver = "2"
members = ["core", "dev", "desktop", "netplay", "server"]

[workspace.dependencies]
emiu2 = { path = "core" }
emiu2-netplay = { path = "netplay" }
emiu2-relay = { path = "server" }
miuchiz-reborn-paths = { git = "https://github.com/coremaze/Miuchiz-Reborn-Paths" }
cpal = "0.15.3"
